# Default values for deployment, this is necessary because we're using a unified helm subchart
deployment:
  # This is the name of the deployment, this is used in a _lot_ of places in the helm charts so lets just specify it
  name: http-proxy

  # What group we're in in gitlab and what namespace we deploy to in kubernetes
  image:
    repository: andrewfarley/docker-kubernetes-apache-proxy
    tag: latest

  # Have a nodeport service, which we manually route from an NLB
  service:
    type: NodePort

  # livenessProbes are used to determine when to restart a container
  # Only specify the values you need to override from the defaults
  livenessProbe:
    enabled: false
    path: /

  # readinessProbes are used to determine when a container is ready to start accepting traffic
  # Only specify the values you need to override from the defaults
  readinessProbe:
    enabled: false
    path: /

  # deployment container resource requests/limits
  # this is set VERY low by default, to be aggressive above resource limiting, please override this if necessary
  # Note: Limits are HARD Limits
  #       Requests are "soft" limits and are what affects HPA (autoscaling) aggressiveness if HPA is enabled
  resources:
    limits:
     cpu: 100m
     memory: 100Mi
    requests:
     cpu: 100m
     memory: 100Mi

  # Enable autoscaling
  autoscaling:
    enabled: false

  ingress:
    enabled: true
    hosts:
      - host: REPLACE_HOSTNAME_IN_ENV_VALUES
        paths:
          - /(/+)?(.*)

  volumes:
    - name: config-volume
      configMap:
        name: http-proxy

  volumeMounts:
    - name: config-volume
      mountPath: /usr/local/apache2/conf/kubernetes
