{
 "title": "Kubernetes Statefulset/Deployment/Daemonset Dashboard",
 "description": "An introspection into the health of any of our services in Kubernetes",
 "tags": [
  "kubernetes",
  "statefulset",
  "deployment",
  "daemonset"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_cpu_usage_seconds_total,namespace)"
   },
   { "name": "choose_one", "query": "choose one ->" },
   {
    "name": "Statefulset",
    "query": "label_values(kube_statefulset_labels{ namespace=~\"$namespace\"}, statefulset)"
   },
   {
    "name": "Deployment",
    "label": "Deployment",
    "query": "label_values(kube_deployment_labels{ namespace=~\"$namespace\"}, deployment)"
   },
   {
    "name": "Daemonset",
    "query": "label_values(kube_daemonset_labels{ namespace=~\"$namespace\"},daemonset)"
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Requests (soft limit/guaranteed)",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 0 }
  },
  {
   "title": "Resource Limits (hard limit / max)",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 0 }
  },
  { "title": "Resource Usage (raw)", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 12, "y": 0 } },
  { "title": "Cluster State", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 0 } },
  {
   "title": "CPUs",
   "type": "singlestat",
   "description": "NOTE: These MAY not be not accurate if you select Env:All if one of the envs differs from the others.  \n\nSorry, Farley can not figure out the magical query for that  :P",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",container=~\"$Statefulset\", resource=\"cpu\"}) / count(kube_pod_container_resource_requests{namespace=~\"$namespace\",container=~\"$Statefulset\", resource=\"cpu\"})\nor\nsum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\", resource=\"cpu\"}) / count(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\", resource=\"cpu\"})\nor\nsum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"^$Daemonset-([[:alnum:]]+)\", resource=\"cpu\"}) / count(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"^$Daemonset-([[:alnum:]]+)\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "description": "NOTE: These MAY not be not accurate if you select Env:All if one of the envs differs from the others.  \n\nSorry, Farley can not figure out the magical query for that  :P",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\nsum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", container=\"$Statefulset\"}) / count(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", container=\"$Statefulset\"}) or\nsum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"}) / count(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"})\nor\nsum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", pod=~\"^$Daemonset-([[:alnum:]]+)\"}) / count(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", pod=~\"^$Daemonset-([[:alnum:]]+)\"})\n)"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "description": "NOTE: These MAY not be not accurate if you select Env:All if one of the envs differs from the others.  \n\nSorry, Farley can not figure out the magical query for that  :P",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\nsum(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"$Statefulset\", resource=\"cpu\"}) / count(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"$Statefulset\", resource=\"cpu\"}) or\nsum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\", resource=\"cpu\"}) / count(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\", resource=\"cpu\"})\nor\nsum(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"^$Daemonset-([[:alnum:]]+)\", resource=\"cpu\"}) / count(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"^$Daemonset-([[:alnum:]]+)\", resource=\"cpu\"})\n)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "description": "NOTE: These MAY not be not accurate if you select Env:All if one of the envs differs from the others.  \n\nSorry, Farley can not figure out the magical query for that  :P",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\nmax(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", container=\"$Statefulset\"}) \nor\nmax(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"})\nor\nmax(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", pod=~\"^$Daemonset-([[:alnum:]]+)\"})\n)"
    }
   ]
  },
  {
   "title": "CPU Usage Raw (per-pod, 1 == 1 CPU)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\nrate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"^$Statefulset-([[:digit:]]+)\", image!=\"\", container!=\"POD\"}[$__interval])\nor\nrate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\", image!=\"\", container!=\"POD\"}[$__interval])\nor\nrate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"^$Daemonset-([[:alnum:]]+)\", image!=\"\", container!=\"POD\"}[$__interval])\n)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Desired",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "\n(\nsum(kube_statefulset_status_replicas{namespace=~\"$namespace\", statefulset=~\"$Statefulset\"}) or \nsum(kube_deployment_status_replicas{namespace=~\"$namespace\", deployment=~\"$Deployment\"}) or \nsum(kube_daemonset_status_desired_number_scheduled{namespace=~\"$namespace\", daemonset=~\"$Daemonset\"}) or\nvector(0)\n)"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\nsum(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\", statefulset=~\"$Statefulset\"}) or \nsum(kube_deployment_status_replicas_available{namespace=~\"$namespace\", deployment=~\"$Deployment\"}) or\nsum(kube_daemonset_status_number_available{namespace=~\"$namespace\", daemonset=~\"$Daemonset\"}) or\nvector(0)\n)"
    }
   ]
  },
  {
   "title": "Updated",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(\nsum(kube_statefulset_status_replicas_current{namespace=~\"$namespace\", statefulset=~\"$Statefulset\"}) or\nsum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\", deployment=~\"$Deployment\"}) or \nsum(kube_daemonset_status_number_ready{namespace=~\"$namespace\", daemonset=~\"$Daemonset\"}) or\nvector(0)\n)"
    }
   ]
  },
  {
   "title": "CPU Usage / K8s Requests (if present)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\nsum(rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"^$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)\"}[$__interval])) by (namespace, pod) / ignoring(pod, container) group_left sum(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=\"$Statefulset\", resource=\"cpu\"}) by (namespace, pod)\nor\nsum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\", image!=\"\", container!=\"POD\"}[$__interval])) by (namespace, pod) / sum(label_replace(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\", resource=\"cpu\"}, \"pod\", \"$1\", \"pod\", \"(.+)\")) by (namespace, pod)\nor\nsum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"^$Daemonset-([[:alnum:]]+)\", image!=\"\", container!=\"POD\"}[$__interval])) by (namespace, pod) / sum(label_replace(kube_pod_container_resource_requests{namespace=~\"$namespace\", pod=~\"^$Daemonset-([[:alnum:]]+)\", resource=\"cpu\"}, \"pod\", \"$1\", \"pod\", \"(.+)\")) by (namespace, pod)\n)\n",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage / K8s Limits (if present)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\nsum(rate (container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"^$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)\"}[$__interval])) by (pod) / ignoring(pod, container) group_left sum(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"$Statefulset\", resource=\"cpu\"})  \nor\nsum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\", image!=\"\", container!=\"POD\"}[$__interval])) by (pod) / sum(label_replace(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\", resource=\"cpu\"}, \"pod\", \"$1\", \"pod\", \"(.+)\")) by (pod)\nor\nsum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"^$Daemonset-([[:alnum:]]+)\", image!=\"\", container!=\"POD\"}[$__interval])) by (pod) / sum(label_replace(kube_pod_container_resource_limits{namespace=~\"$namespace\", pod=~\"^$Daemonset-([[:alnum:]]+)\", resource=\"cpu\"}, \"pod\", \"$1\", \"pod\", \"(.+)\")) by (pod)\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Available / Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\nsum(kube_statefulset_status_replicas{namespace=~\"$namespace\", statefulset=~\"$Statefulset\"}) or \nsum(kube_deployment_status_replicas{namespace=~\"$namespace\", deployment=~\"$Deployment\"}) or \nsum(kube_daemonset_status_desired_number_scheduled{namespace=~\"$namespace\", daemonset=~\"$Daemonset\"}) or\nvector(0)\n)",
     "legendFormat": "Desired"
    },
    {
     "expr": "(\nsum(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\", statefulset=~\"$Statefulset\"}) or \nsum(kube_deployment_status_replicas_available{namespace=~\"$namespace\", deployment=~\"$Deployment\"}) or\nsum(kube_daemonset_status_number_available{namespace=~\"$namespace\", daemonset=~\"$Daemonset\"}) or\nvector(0)\n)\n",
     "legendFormat": "Available"
    },
    {
     "expr": "(\nsum(kube_statefulset_status_replicas{namespace=~\"$namespace\", statefulset=~\"$Statefulset\"}) - sum(kube_statefulset_status_replicas_ready{namespace=~\"$namespace\", statefulset=~\"$Statefulset\"}) or\nsum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\", deployment=~\"$Deployment\"}) or \nsum(kube_daemonset_status_desired_number_scheduled{namespace=~\"$namespace\", daemonset=~\"$Daemonset\"}) - sum(kube_daemonset_status_number_ready{namespace=~\"$namespace\", daemonset=~\"$Daemonset\"}) or\nvector(0)\n)\n",
     "legendFormat": "Unavailable"
    },
    {
     "expr": "(\nsum(kube_statefulset_status_replicas_current{namespace=~\"$namespace\", statefulset=~\"$Statefulset\"}) or\nsum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\", deployment=~\"$Deployment\"}) or \nsum(kube_daemonset_status_number_ready{namespace=~\"$namespace\", daemonset=~\"$Daemonset\"}) or\nvector(0)\n)",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "CPU Usage Raw (Aggregated)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\nsum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"^$Statefulset-([[:digit:]]+)\", image!=\"\", container!=\"POD\"}[$__interval])) \nor\nsum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\", image!=\"\", container!=\"POD\"}[$__interval]))\nor\nsum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"^$Daemonset-([[:alnum:]]+)\", image!=\"\", container!=\"POD\"}[$__interval]))\n)\n",
     "legendFormat": "Total CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage (% of request) (if present)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\nmax (container_memory_working_set_bytes{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)\"}) by (namespace, pod) \n/  ignoring(pod, container, namespace) group_left\nmax(sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", container=\"$Statefulset\"}) / count(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\", container=\"$Statefulset\"})) \nor\nmax (container_memory_working_set_bytes{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"}) by (namespace, pod) \n/  ignoring(pod, container, namespace) group_left\nmax(sum( kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",  pod=~\"$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"} ) / count(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",  pod=~\"$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"})) \nor\nmax (container_memory_working_set_bytes{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Daemonset-([[:alnum:]]+)\"}) by (namespace, pod) \n/  ignoring(pod, container, namespace) group_left\nmax(sum( kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",  pod=~\"$Daemonset-([[:alnum:]]+)\"} ) / count(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\",  pod=~\"$Daemonset-([[:alnum:]]+)\"})) \n\n)\n",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (% of limit) (if present)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\nmax (container_memory_working_set_bytes{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)\"}) by (namespace, pod) \n/  ignoring(pod, container, namespace) group_left\nmax(sum(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", container=\"$Statefulset\"}) / count(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", container=\"$Statefulset\"})) \nor\nmax (container_memory_working_set_bytes{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"}) by (namespace, pod) \n/  ignoring(pod, container, namespace) group_left\nmax(sum( kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\",  pod=~\"$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"} ) / count(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\",  pod=~\"$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"})) \nor\nmax (container_memory_working_set_bytes{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Daemonset-([[:alnum:]]+)\"}) by (namespace, pod) \n/  ignoring(pod, container, namespace) group_left\nmax(sum( kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\",  pod=~\"$Daemonset-([[:alnum:]]+)\"} ) / count(kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\",  pod=~\"$Daemonset-([[:alnum:]]+)\"})) \n\n)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  { "title": "Disk Usage", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 9 } },
  {
   "title": "used %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(100 * (kubelet_volume_stats_used_bytes{ persistentvolumeclaim=~\".*$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)\"} \n/ \nkubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)\"}))"
    }
   ]
  },
  {
   "title": "used max",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{ persistentvolumeclaim=~\".*$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)$\"})"
    }
   ]
  },
  {
   "title": "avail max",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 10 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)\"})"
    }
   ]
  },
  {
   "title": "RAM Usage (Per-pod)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\nmax (container_memory_working_set_bytes{namespace=~\"$namespace\", id!=\"/\",container!=\"POD\",pod=~\"^$Statefulset-([[:digit:]]+)\"}) by (namespace, pod)\nor\nmax (container_memory_working_set_bytes{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"}) by (namespace, pod)\nor\nmax (container_memory_working_set_bytes{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Daemonset-([[:alnum:]]+)\"}) by (namespace, pod)\n)",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "used total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{ persistentvolumeclaim=~\".*$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)$\"})"
    }
   ]
  },
  {
   "title": "avail total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\".*$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)\"})"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(100 * (kubelet_volume_stats_used_bytes{ persistentvolumeclaim=~\".*$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)\"} \n/ \nkubelet_volume_stats_capacity_bytes{ persistentvolumeclaim=~\".*$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)\"})) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "RAM Usage (Aggregated)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\nsum(container_memory_working_set_bytes{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Statefulset-([[:digit:]]+)\", image!=\"\",container!=\"POD\"})\nor\nsum(container_memory_working_set_bytes{namespace=~\"$namespace\", id!=\"/\",container!=\"POD\",pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"})\nor\nsum(container_memory_working_set_bytes{namespace=~\"$namespace\", id!=\"/\",container!=\"POD\",pod=~\"^$Daemonset-([[:alnum:]]+)\"})\n)"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max(kubelet_volume_stats_used_bytes{ persistentvolumeclaim=~\".*$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  { "title": "Network Usage", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Network I/O (per-pod)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(\nsum (rate (container_network_receive_bytes_total{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)$\"}[$__interval])) by (namespace, pod) \nor\nsum (rate (container_network_receive_bytes_total{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"}[$__interval])) by (namespace, pod)\nor\nsum (rate (container_network_receive_bytes_total{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Daemonset-([[:alnum:]]+)\"}[$__interval])) by (namespace, pod)\n)",
     "legendFormat": "-> {{ namespace }} - {{ pod }}"
    },
    {
     "expr": "- (\nsum( rate (container_network_transmit_bytes_total{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)$\"}[$__interval])) by (pod) or\nsum( rate (container_network_transmit_bytes_total{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"}[$__interval])) by (pod)\n)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "Network I/O (aggregated)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "(\nsum (rate (container_network_receive_bytes_total{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)$\"}[$__interval]))  \nor\nsum (rate (container_network_receive_bytes_total{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"}[$__interval])) \nor\nsum (rate (container_network_receive_bytes_total{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Daemonset-([[:alnum:]]+)\"}[$__interval])) \n)",
     "legendFormat": "-> $Statefulset$Deployment$Daemonset"
    },
    {
     "expr": "- (\nsum( rate (container_network_transmit_bytes_total{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Statefulset-(?:0|1|2|3|4|5|6|7|8|9)$\"}[$__interval])) \nor\nsum( rate (container_network_transmit_bytes_total{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Deployment-([[:alnum:]]+)-([[:alnum:]]+)\"}[$__interval])) \nor\nsum( rate (container_network_transmit_bytes_total{namespace=~\"$namespace\", id!=\"/\",pod=~\"^$Daemonset-([[:alnum:]]+)\"}[$__interval])) \n)",
     "legendFormat": "<- $Statefulset"
    }
   ]
  }
 ]
}