{
 "title": "Node Metrics (aggregated)",
 "tags": [
  "manual",
  "infra",
  "k8s-nodes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app:",
    "query": "label_values(node_exporter_build_info, app)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPUs",
   "type": "singlestat",
   "description": "Total number of CPU cores across all the servers",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{app=~\"$app\"}) by (cpu, instance))"
    }
   ]
  },
  {
   "title": "Disk Space Total",
   "type": "singlestat",
   "description": "Total Root Filesystem Size between all the servers",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 0 },
   "format": "bytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{app=~\"$app\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "Uptime (average)",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "avg(node_time_seconds{app=~\"$app\"}) - avg(node_boot_time_seconds{app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "CPU Usage (average)",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together averaged across all servers in this app",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(count by (instance, cpu) (node_cpu_seconds_total{app=~\"$app\"}))\n- \navg(sum by (mode) (irate(node_cpu_seconds_total{mode='idle',app=~\"$app\"}[5m]))))\n/\ncount(count by (instance, cpu) (node_cpu_seconds_total{app=~\"$app\"})) * 100"
    }
   ]
  },
  {
   "title": "Used RAM percent",
   "type": "singlestat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - avg((node_memory_MemAvailable_bytes{app=~\"$app\"} * 100) / node_memory_MemTotal_bytes{app=\"$app\"})"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "singlestat",
   "description": "Used disk space on /",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - avg((node_filesystem_avail_bytes{app=~\"kafka\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{app=~\"kafka\",mountpoint=\"/\",fstype!=\"rootfs\"})\n"
    }
   ]
  },
  {
   "title": "Used Swap (aggregated, if present)",
   "type": "singlestat",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{app=~\"gitlab\"} - node_memory_SwapFree_bytes{app=~\"gitlab\"}) / (node_memory_SwapTotal_bytes{app=~\"gitlab\"})\n > 0) * 100"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM on the servers combined",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Total Swap",
   "type": "singlestat",
   "description": "Total SWAP combined",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_SwapTotal_bytes{app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_disk_reads_completed_total{app=~\"kafka\", device!~\"dm.*\"}[5m]))",
     "legendFormat": "Reads completed"
    },
    {
     "expr": "sum(irate(node_disk_writes_completed_total{app=~\"$app\", device!~\"dm.*\"}[5m]))",
     "legendFormat": "Writes completed"
    }
   ]
  },
  {
   "title": "Network Traffic Overview",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes", "label": "Sent (-) / Receive (+)" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{app=~\"$app\", device=~\"eth.*\"}[$__interval]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{app=~\"$app\", device=~\"eth.*\"}[$__interval]))",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}