{
 "title": "RabbitMQ Monitoring",
 "description": "Review our ingress controllers traffic",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "queue",
    "query": "label_values(rabbitmq_queue_messages,queue)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Messages In Queue",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(rabbitmq_queue_messages_ready{kubernetes_name=\"sci-rabbitmq-discovery\"}) by (queue))"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_connections{kubernetes_name=\"sci-rabbitmq-discovery\"})"
    }
   ]
  },
  {
   "title": "Ready messages",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max(rabbitmq_queue_messages_ready{kubernetes_name=\"sci-rabbitmq-discovery\", queue=~\"$queue\"}) by (queue))"
    }
   ]
  },
  {
   "title": "Messages in Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rabbitmq_queue_messages_ready{kubernetes_name=\"sci-rabbitmq-discovery\"}) by (queue)",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Total Open Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(rabbitmq_connections)", "legendFormat": "{{ingress}}" }
   ]
  },
  { "title": "RabbitMQ Pod Specifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rabbitmq_build_info{kubernetes_name=\"sci-rabbitmq-discovery\"} * on(instance) group_left(kubernetes_node) rabbitmq_identity_info{kubernetes_name=\"sci-rabbitmq-discovery\"}"
    }
   ]
  }
 ]
}